project:
  type: website
  output-dir: docs

website:
  title: "Flows of Norwegian Scholars"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    embed-resources: true